### ISSUE TITLE
No such thing as ./configure

### ISSUE THREAD

**Issue by angrypig555** [naggety/picotts#11]
I downloaded picotts then i installed it using the manual but when i got to the stap that says run:
./configure
make
it showed me an error that ./configure doesnt exist

**Comment by ihuguet** [comment]
Then, either you didn't run `autogen.sh` or it failed. Run it again and paste any errors you get.

**Comment by Wend1go** [comment]
In case anyone else runs into this problem, you need to install the following packages on Ubuntu based distros before you can start the compilation process:
`sudo apt install automake libtool libpopt-dev`
