### ISSUE TITLE
wav file

### ISSUE THREAD

**Issue by InnovMuch** [naggety/picotts#13]
Hello,
Does it work on the armv7l architecture? I've installed it successfully, but when I try to generate a WAV file, the audio output sounds strange. Any idea what could be causing this?

**Comment by ihuguet** [comment]
No idea, sorry. I guess that you should try to reproduce the same wav file in other device. And to reproduce a different wav that works fine in another device on this device. That way you will find if the problem is in the generation of the wav or in the audio playback of your device.

**Comment by ihuguet** [comment]
I used it on an Allwinner A20 which is armv7, so I guess that I have to say that it works on armv7
